// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXlst4X6mS9C7t3LcI-ZrK_Bqsuq9Nj4',
    appId: '1:746568678772:web:a7c8153d8d9cb5b91bc021',
    messagingSenderId: '746568678772',
    projectId: 'projeto3-97721',
    authDomain: 'projeto3-97721.firebaseapp.com',
    storageBucket: 'projeto3-97721.firebasestorage.app',
    measurementId: 'G-B0TYWSLV9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAMN4U1oq7r_rgA9IMaq2hc2JDhx-5n8',
    appId: '1:746568678772:android:cc870fd5796384e61bc021',
    messagingSenderId: '746568678772',
    projectId: 'projeto3-97721',
    storageBucket: 'projeto3-97721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpySdyPcDgnc79h6Gv2AD9QWrJIiRfPn4',
    appId: '1:746568678772:ios:33f1047916c10a051bc021',
    messagingSenderId: '746568678772',
    projectId: 'projeto3-97721',
    storageBucket: 'projeto3-97721.firebasestorage.app',
    iosBundleId: 'com.example.projetos3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpySdyPcDgnc79h6Gv2AD9QWrJIiRfPn4',
    appId: '1:746568678772:ios:33f1047916c10a051bc021',
    messagingSenderId: '746568678772',
    projectId: 'projeto3-97721',
    storageBucket: 'projeto3-97721.firebasestorage.app',
    iosBundleId: 'com.example.projetos3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXlst4X6mS9C7t3LcI-ZrK_Bqsuq9Nj4',
    appId: '1:746568678772:web:015bdfa19416e0d41bc021',
    messagingSenderId: '746568678772',
    projectId: 'projeto3-97721',
    authDomain: 'projeto3-97721.firebaseapp.com',
    storageBucket: 'projeto3-97721.firebasestorage.app',
    measurementId: 'G-W8YQN7FE9H',
  );
}
